version: '2'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: /usr/src/app
    env_file:
      - '.env.backend'
    environment: 
      RAILS_ENV: production
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
  nginx:
    image: nginx:1.11
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./shared:/usr/src/app/shared
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
  postgres:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
