version: '2'
services:
  backend:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    ports:
      - "13000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: /u/apps/bullsandcows
    env_file:
      - '.env.postgres.secret'
      - '.env.backend'
      - '.env.backend.secret'
  postgres:
    image: postgres:9.5.3
    ports:
      - "15432:5432"
    env_file:
      - '.env.postgres.secret'

  rspec:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: /u/apps/bullsandcows
    environment:
      RAILS_ENV: test
    env_file:
      - '.env.postgres.secret'
      - '.env.backend'
      - '.env.backend.test'
    command: bundle exec rspec -fd
