version: '2'
services:
  backend:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    working_dir: /u/apps/bullsandcows
    environment:
      RAILS_ENV: development
    env_file:
      - '.env.backend'
      - '.env.backend.secret'
      - '.env.postgres.secret'
  postgres:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    env_file:
      - '.env.postgres.secret'
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  rspec:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    working_dir: /u/apps/bullsandcows
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
    env_file:
      - '.env.backend'
      - '.env.backend.test'
    command: bundle exec rspec -fd
