version: '2'
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "13000:3000"
    links:
      - mysql
      - postgres
    depends_on:
      - postgres
    env_file:
      - '.env.postgres'
      - '.env.web'
      - '.env.web.secret'
  mysql:
    image: library/mysql:5.6.22
    ports:
      - "13306:3306"
    env_file:
      - '.env.mysql'
  postgres:
    image: postgres:9.5.3
    ports:
      - "15432:5432"
    env_file:
      - '.env.postgres'