version: '2'
services:
  backend:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    working_dir: /usr/src/app
    environment:
      RAILS_ENV: development
    env_file:
      - '.env.backend'
      - '.env.backend.secret'
      - '.env.postgres.secret'
    command: bundle exec rails s --binding 0.0.0.0
  nginx:
    image: nginx:1.11
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
  postgres:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    env_file:
      - '.env.postgres.secret'
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  rspec:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    working_dir: /usr/src/app
    environment:
      RAILS_ENV: test
    env_file:
      - '.env.backend'
      - '.env.backend.test'
      - '.env.postgres.secret'
    command: bash -c "rake db:setup && bundle exec rspec"
