version: '2'
services:
  postgres:
    image: postgres:9.5.3
    ports:
      - "15432:5432"
    env_file:
      - '.env.postgres.test'
  redis:
    image: redis:3.2
    ports:
      - "16379:6379"
  rspec:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    working_dir: /u/apps/bullsandcows
    environment:
      RAILS_ENV: test
    env_file:
      - '.env.backend'
      - '.env.backend.test'
      - '.env.postgres.test'
    command: bash -c "sleep 5 && rake db:setup && bundle exec rspec -fd"
