version: '2'
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "13000:3000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - '.env.db'
      - '.env.web'
  db:
    image: library/mysql:5.6.22
    ports:
      - "13306:3306"
    env_file:
      - '.env.db'
