version: '2'
services:
  web:
    build: .
    volumes:
      - .:/u/apps/bullsandcows
    ports:
      - "13000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: /u/apps/bullsandcows
    env_file:
      - '.env.postgres'
      - '.env.web'
      - '.env.web.secret'
  postgres:
    image: postgres:9.5.3
    ports:
      - "15432:5432"
    env_file:
      - '.env.postgres'